import * as assert from 'node:assert';
import { runBuildFixLoop } from '../../buildFixLoop';
import type { BuildResult, RunBuildFn } from '../../buildVerify';
import type { GenerateResult, OutputSink, RunAgentOptions } from '../../agentRuntime';

class RecordingSink implements OutputSink {
  readonly lines: string[] = [];
  appendLine(value: string): void {
    this.lines.push(value);
  }
}

const CWD = '/tmp/workspace';
const WRITTEN = ['src/app/a/a.component.ts'];

function buildFail(errorsBlock: string): BuildResult {
  return { success: false, output: errorsBlock };
}

const OUR_FILE_ERROR = [
  "X [ERROR] TS2353: Object literal may only specify known properties. [plugin angular-compiler]",
  '',
  '    src/app/a/a.component.ts:10:5:',
  '',
].join('\n');

const OTHER_FILE_ERROR = [
  'X [ERROR] TS2322: pre-existing type error. [plugin angular-compiler]',
  '',
  '    src/app/pre-existing/pre-existing.component.ts:3:1:',
  '',
].join('\n');

describe('runBuildFixLoop', () => {
  it('reports success without calling the agent when the initial build already passes', async () => {
    const sink = new RecordingSink();
    let agentCalls = 0;
    const buildRunner: RunBuildFn = async () => ({ success: true, output: 'Application bundle generation complete.' });
    const agentRunner = async (): Promise<GenerateResult> => {
      agentCalls++;
      return { filesWritten: [], succeeded: true };
    };

    const result = await runBuildFixLoop(
      { cwd: CWD, filesWritten: WRITTEN, systemPrompt: 'sys' },
      sink,
      buildRunner,
      agentRunner,
    );

    assert.strictEqual(result.finalSuccess, true);
    assert.strictEqual(result.attempts, 1);
    assert.strictEqual(agentCalls, 0);
    assert.ok(sink.lines.some((l) => l.includes('tentativa 1')));
  });

  it('fixes a single error in a generated file and verifies with a passing rebuild', async () => {
    const sink = new RecordingSink();
    let buildCall = 0;
    let agentCalls = 0;
    const buildRunner: RunBuildFn = async () => {
      buildCall++;
      return buildCall === 1 ? buildFail(OUR_FILE_ERROR) : { success: true, output: 'ok' };
    };
    const agentRunner = async (options: RunAgentOptions): Promise<GenerateResult> => {
      agentCalls++;
      assert.ok(options.userPrompt.includes('src/app/a/a.component.ts'));
      assert.strictEqual(options.systemPrompt, 'sys');
      return { filesWritten: [], succeeded: true };
    };

    const result = await runBuildFixLoop(
      { cwd: CWD, filesWritten: WRITTEN, systemPrompt: 'sys' },
      sink,
      buildRunner,
      agentRunner,
    );

    assert.strictEqual(result.finalSuccess, true);
    assert.strictEqual(result.attempts, 2);
    assert.strictEqual(agentCalls, 1);
    assert.deepStrictEqual(result.fixedFiles, ['src/app/a/a.component.ts']);
  });

  it('does not call the agent when the failing file was not generated by this run', async () => {
    const sink = new RecordingSink();
    let agentCalls = 0;
    const buildRunner: RunBuildFn = async () => buildFail(OTHER_FILE_ERROR);
    const agentRunner = async (): Promise<GenerateResult> => {
      agentCalls++;
      return { filesWritten: [], succeeded: true };
    };

    const result = await runBuildFixLoop(
      { cwd: CWD, filesWritten: WRITTEN, systemPrompt: 'sys' },
      sink,
      buildRunner,
      agentRunner,
    );

    assert.strictEqual(result.finalSuccess, false);
    assert.strictEqual(agentCalls, 0);
    assert.strictEqual(result.preexistingErrors.length, 1);
    assert.ok(result.preexistingErrors[0].file?.includes('pre-existing'));
  });

  it('stops after 3 fix attempts if the build keeps failing, calling the agent exactly 3 times', async () => {
    const sink = new RecordingSink();
    let agentCalls = 0;
    const buildRunner: RunBuildFn = async () => buildFail(OUR_FILE_ERROR);
    const agentRunner = async (): Promise<GenerateResult> => {
      agentCalls++;
      return { filesWritten: [], succeeded: true };
    };

    const result = await runBuildFixLoop(
      { cwd: CWD, filesWritten: WRITTEN, systemPrompt: 'sys' },
      sink,
      buildRunner,
      agentRunner,
    );

    assert.strictEqual(result.finalSuccess, false);
    assert.strictEqual(agentCalls, 3);
    assert.strictEqual(result.attempts, 4); // 1 inicial + 3 reconstruções de verificação
    assert.strictEqual(result.remainingErrors.length, 1);
  });

  it('stops early without further rebuilds if the fix attempt itself fails to run', async () => {
    const sink = new RecordingSink();
    let buildCalls = 0;
    let agentCalls = 0;
    const buildRunner: RunBuildFn = async () => {
      buildCalls++;
      return buildFail(OUR_FILE_ERROR);
    };
    const agentRunner = async (): Promise<GenerateResult> => {
      agentCalls++;
      return { filesWritten: [], succeeded: false, errorMessage: 'CLI indisponível' };
    };

    const result = await runBuildFixLoop(
      { cwd: CWD, filesWritten: WRITTEN, systemPrompt: 'sys' },
      sink,
      buildRunner,
      agentRunner,
    );

    assert.strictEqual(result.finalSuccess, false);
    assert.strictEqual(agentCalls, 1);
    assert.strictEqual(buildCalls, 1); // só o build inicial — não tenta reconstruir após falha do próprio fix
    assert.ok(sink.lines.some((l) => l.includes('CLI indisponível')));
  });
});
